//
//  SchoolNames.swift
//  RealmVsSwiftData
//
//  Created by Jacob Bartlett on 02/05/2024.
//

let schoolNames = [
    "Ark Greenwich Free School",
    "Eltham Hill School",
    "The Halley Academy",
    "Harris Academy Greenwich",
    "The John Roan School",
    "Leigh Academy Blackheath",
    "Plumstead Manor School",
    "Royal Greenwich Trust School",
    "St Mary Magdalene CE All Through School",
    "St Paul's Academy",
    "St Thomas More Catholic School",
    "St Ursula's Convent School",
    "Stationers' Crown Woods Academy",
    "Thomas Tallis School",
    "Woolwich Polytechnic School for Boys",
    "Woolwich Polytechnic School for Girls",
    "Alderwood School",
    "Alexander McLeod School",
    "Bannockburn School",
    "Bishop John Robinson CE School",
    "Boxgrove School",
    "Brooklands School",
    "Cardwell School",
    "Charlton Manor School",
    "Cherry Orchard School",
    "Christ Church CE School, Greenwich",
    "Christ Church CE School, Shooters Hill",
    "Conway School",
    "De Lucy School",
    "Deansfield School",
    "Discovery School",
    "Ealdham School",
    "Eglinton School",
    "Eltham CE School",
    "Fossdene School",
    "Foxfield School",
    "Gallions Mount School",
    "Gordon School",
    "Greenacres School",
    "Greenslade School",
    "Haimo School",
    "Halstow School",
    "Hawksmoor School",
    "Henwick School",
    "Heronsgate School",
    "Holy Family RC School",
    "Horn Park School",
    "Invicta School",
    "James Wolfe School",
    "Kidbrooke Park School",
    "Linton Mead School",
    "Meridian School",
    "Middle Park School",
    "Millennium School",
    "Montbelle School",
    "Morden Mount School",
    "Mulgrave School",
    "Nightingale School",
    "Notre Dame RC School",
    "Our Lady of Grace RC School",
    "Plumcroft School",
    "Rockliffe Manor School",
    "St Alfege with St Peter's CE School",
    "St Joseph's RC School",
    "St Margaret Clitherow RC School",
    "St Margaret's CE School",
    "St Mary Magdalene CE All Through School",
    "St Mary's RC School",
    "St Patrick's RC School",
    "St Peter's RC School",
    "St Thomas A Becket RC School",
    "St Thomas More RC School",
    "Sherington School",
    "South Rise School",
    "Thorntree School",
    "Timbercroft School",
    "Windrush School",
    "Wingfield School",
    "Woodhill School",
    "Wyborne School",
    "Adamsrill School",
    "All Saints' CE School",
    "Ashmead School",
    "Athelney School",
    "Baring School",
    "Beecroft Garden School",
    "Brindishe Green School",
    "Brindishe Lee School",
    "Brindishe Manor School",
    "Childeric School",
    "Cooper's Lane School",
    "Dalmain School",
    "Deptford Park School",
    "Downderry School",
    "Edmund Waller School",
    "Elfrida School",
    "Eliot Bank School",
    "Fairlawn School",
    "Forster Park School",
    "Good Shepherd RC School",
    "Gordonbrock School",
    "Grinling Gibbons School",
    "Haberdashers' Hatcham Temple Grove",
    "Haberdashers' Hatcham Temple Grove Free School",
    "Haberdashers' Knights Temple Grove",
    "Haseltine School",
    "Holbeach School",
    "Holy Cross RC School",
    "Holy Trinity CE School",
    "Horniman School",
    "John Ball School",
    "John Stainer Community School",
    "Kelvin Grove School",
    "Kender School",
    "Kilmorie School",
    "Launcelot School",
    "Lucas Vale School",
    "Marvels Lane School",
    "Myatt Garden School",
    "Our Lady and St Philip Neri RC School",
    "Perrymount School",
    "Prendergast Ladywell School",
    "Prendergast Vale School",
    "Rathfern School",
    "Rushey Green School",
    "St Augustine's RC School",
    "St Bartholomews's CE School",
    "St George's CE School",
    "St James's Hatcham CE School",
    "St John Baptist Southend CE School",
    "St Joseph's RC School",
    "St Margaret's Lee CE School",
    "St Mary Magdalen's RC School",
    "St Mary's Lewisham CE School",
    "St Matthew Academy",
    "St Michael's CE School",
    "St Saviour's RC School",
    "St Stephen's CE School",
    "St William of York RC School",
    "St Winifred's RC School",
    "Sandhurst School",
    "Stillness Infant School",
    "Stillness Junior School",
    "Tidemill Academy",
    "Torridon School",
    "Trinity Church of England School",
    "Turnham Academy",
    "Twin Oaks School",
    "Abacus Belsize School",
    "Argyle School",
    "Beckford School",
    "Brecknock School",
    "Brookfield School",
    "Christ Church School, Hampstead",
    "Christ Church School, Redhill Street",
    "Christopher Hatton School",
    "Edith Neville School",
    "Eleanor Palmer School",
    "Emmanuel School",
    "Fitzjohn's School",
    "Fleet School",
    "Gospel Oak School",
    "Hampstead Parochial School",
    "Hawley School",
    "Holy Trinity and St Silas School",
    "Holy Trinity Trinity Walk School",
    "Kentish Town School",
    "Kings Cross Academy",
    "Kingsgate School",
    "Netley School",
    "New End School",
    "Our Lady School",
    "Primrose Hill School",
    "Rhyl Community School",
    "Richard Cobden School",
    "Rosary School",
    "St Alban's School",
    "St Eugene de Mazenod School",
    "St George the Martyr School",
    "St Joseph's School",
    "St Luke's School",
    "St Mary & St Pancras School",
    "St Mary's Kilburn School",
    "St Michael's School",
    "St Patrick's School",
    "St Paul's School",
    "Torriano School",
    "Barnehurst Infant School",
    "Barnehurst Junior School",
    "Barrington School",
    "Bedonwell Infant School",
    "Bedonwell Junior School",
    "Belmont Academy",
    "Belvedere Infant School",
    "Belvedere Junior School",
    "Birkbeck School",
    "Bishop Ridley CE School",
    "Brampton Academy",
    "Burnt Oak Junior School",
    "Bursted Wood School",
    "Castilion School",
    "Chatsworth Infant School",
    "Christ Church CE School",
    "Crook Log School",
    "Danson School",
    "Days Lane School",
    "Dulverton School",
    "East Wickham Academy",
    "Eastcote Academy",
    "Foster's School",
    "Gravel Hill School",
    "Haberdashers' Crayford Temple Grove",
    "Haberdashers' Slade Green Temple Grove",
    "Harris Garrard Academy",
    "Hillsgrove School",
    "Holy Trinity Lamorbey CE School",
    "Hook Lane School",
    "Hope Community School",
    "Hurst School",
    "Jubilee School",
    "Lessness Heath School",
    "Lime Wood School",
    "Longlands School",
    "Mayplace School",
    "Normandy School",
    "Northumberland Heath School",
    "Northwood School",
    "Old Bexley CE School",
    "Orchard School",
    "Our Lady of the Rosary RC School",
    "Parkway School",
    "Peareswood School",
    "Pelham School",
    "Pelham School",
    "Royal Park Academy",
    "St Augustine of Canterbury CE School",
    "St Fidelis RC School",
    "St John Fisher RC School",
    "St Joseph's RC School",
    "St Michael's East Wickham CE School",
    "St Paulinus CE School",
    "St Paul's CE School",
    "St Peter Chanel RC School",
    "St Stephen's RC School",
    "St Thomas More RC School",
    "Sherwood Park School",
    "Upland School",
    "Upton School",
    "Willow Bank School"
]
