//
//  SchoolLocations.swift
//  RealmVsSwiftData
//
//  Created by Jacob Bartlett on 02/05/2024.
//

let schoolLocations = [
    "Amber Valley",
    "Borough of Ashford",
    "Borough of Basildon",
    "Basingstoke and Deane",
    "Borough of Bedford",
    "Blackburn with Darwen",
    "Borough of Blackpool",
    "Borough of Boston",
    "Bracknell Forest",
    "Borough of Brentwood",
    "Brighton and Hove",
    "Bristol",
    "Borough of Broxbourne",
    "Borough of Broxtowe",
    "Borough of Burnley",
    "Cambridge",
    "City of Canterbury",
    "Castle Point",
    "Borough of Charnwood",
    "City of Chelmsford",
    "Cheltenham",
    "Cheshire East",
    "Cheshire West and Chester",
    "Borough of Chesterfield",
    "Borough of Chorley",
    "City of Colchester",
    "Crawley",
    "Dacorum",
    "Borough of Darlington",
    "Borough of Dartford",
    "Derby",
    "East Staffordshire",
    "Eastbourne",
    "Borough of Eastleigh",
    "Borough of Elmbridge",
    "Epsom and Ewell",
    "Borough of Erewash",
    "Exeter",
    "Borough of Fareham",
    "Borough of Fylde",
    "Borough of Gedling",
    "Gloucester",
    "Gosport",
    "Gravesham",
    "Borough of Great Yarmouth",
    "Borough of Guildford",
    "Borough of Halton",
    "Borough of Hartlepool",
    "Hastings",
    "Borough of Havant",
    "Hertsmere",
    "High Peak, Derbyshire",
    "Hinckley and Bosworth",
    "Kingston upon Hull",
    "Hyndburn",
    "Ipswich",
    "King's Lynn and West Norfolk",
    "City of Lancaster",
    "Leicester",
    "Lincoln, England",
    "Luton",
    "Borough of Maidstone",
    "Medway",
    "Borough of Melton",
    "Borough of Middlesbrough",
    "City of Milton Keynes",
    "Borough of Newcastle-under-Lyme",
    "North East Lincolnshire",
    "North Lincolnshire",
    "North Warwickshire",
    "Norwich",
    "Nottingham",
    "Nuneaton and Bedworth",
    "Oadby and Wigston",
    "Oxford",
    "Borough of Pendle",
    "City of Peterborough",
    "Plymouth",
    "Portsmouth",
    "City of Preston, Lancashire",
    "Reading, Berkshire",
    "Redcar and Cleveland",
    "Redditch",
    "Reigate and Banstead",
    "Ribble Valley",
    "Borough of Rossendale",
    "Borough of Rugby",
    "Borough of Runnymede",
    "Rushcliffe",
    "Rushmoor",
    "Borough of Slough",
    "South Ribble",
    "Southampton",
    "Southend-on-Sea",
    "Borough of Spelthorne",
    "St Albans City and District",
    "Borough of Stafford",
    "Stevenage",
    "Borough of Stockton-on-Tees",
    "Stoke-on-Trent",
    "Surrey Heath",
    "Borough of Swale",
    "Borough of Swindon",
    "Tamworth, Staffordshire",
    "Telford and Wrekin",
    "Test Valley",
    "Borough of Tewkesbury",
    "Thurrock",
    "Tonbridge and Malling",
    "Torbay",
    "Borough of Tunbridge Wells",
    "Borough of Warrington",
    "Watford",
    "Borough of Waverley",
    "Welwyn Hatfield",
    "West Devon",
    "West Lancashire",
    "City of Winchester",
    "Royal Borough of Windsor and Maidenhead",
    "Woking",
    "Borough of Wokingham",
    "Worcester, England",
    "Worthing",
    "Borough of Wyre",
    "City of York"
]
